// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWdgPX8E9bscX_w5UcTKdi5i1uUrF3yj0',
    appId: '1:1062686009099:web:badb66275865ff4328240e',
    messagingSenderId: '1062686009099',
    projectId: 'mi-diario-de-montana',
    authDomain: 'mi-diario-de-montana.firebaseapp.com',
    storageBucket: 'mi-diario-de-montana.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9e7upCU2Wmyxwn3QNd3Tcb0MzRs0x6Zo',
    appId: '1:1062686009099:android:e57649abc7aad8bb28240e',
    messagingSenderId: '1062686009099',
    projectId: 'mi-diario-de-montana',
    storageBucket: 'mi-diario-de-montana.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE5PVkGKHTCt1hNXYwP15jxmxws-_IdfQ',
    appId: '1:1062686009099:ios:28bb98ce52caf35d28240e',
    messagingSenderId: '1062686009099',
    projectId: 'mi-diario-de-montana',
    storageBucket: 'mi-diario-de-montana.firebasestorage.app',
    iosBundleId: 'com.example.miDiarioDeMontana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE5PVkGKHTCt1hNXYwP15jxmxws-_IdfQ',
    appId: '1:1062686009099:ios:28bb98ce52caf35d28240e',
    messagingSenderId: '1062686009099',
    projectId: 'mi-diario-de-montana',
    storageBucket: 'mi-diario-de-montana.firebasestorage.app',
    iosBundleId: 'com.example.miDiarioDeMontana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWdgPX8E9bscX_w5UcTKdi5i1uUrF3yj0',
    appId: '1:1062686009099:web:ee619d0a45f80fee28240e',
    messagingSenderId: '1062686009099',
    projectId: 'mi-diario-de-montana',
    authDomain: 'mi-diario-de-montana.firebaseapp.com',
    storageBucket: 'mi-diario-de-montana.firebasestorage.app',
  );
}
